import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { useParams, useNavigate } from 'react-router-dom';
import { StreamChat } from 'stream-chat';
import { Chat, Channel, Window, ChannelHeader, MessageList, MessageInput, Thread } from 'stream-chat-react';
import { useStreamSession } from '../context/StreamSessionContext';
import { useTheme } from '../context/ThemeContext';
import axios from '../utils/axiosInstance';
import Button from '../components/ui/Button';
import { FaArrowLeft } from 'react-icons/fa';

const apiKey = 'p6yehc4e2xgg'; // Replace with actual key or env var

const ChatPage = () => {
    const { appointmentId } = useParams();
    const navigate = useNavigate();
    const { sessionData, setSession } = useStreamSession();
    const [chatClient, setChatClient] = useState(null);
    const [channel, setChannel] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const initChat = async () => {
            let currentSession = sessionData;
            console.log('Initial sessionData:', sessionData);

            if (!currentSession || currentSession.chatChannelId !== `chat_${appointmentId}`) {
                console.log('Fetching new token...');
                try {
                    const token = localStorage.getItem('token');
                    const { data } = await axios.post('/v1/stream/token',
                        { appointmentId, purpose: 'chat' },
                        {
                            headers: { Authorization: `Bearer ${token}` },
                            withCredentials: true
                        }
                    );
                    console.log('API Response:', data);
                    if (data.status === 'success') {
                        currentSession = data.data;
                        setSession(currentSession);
                    }
                } catch (error) {
                    console.error('Error fetching token:', error);
                    toast.error('Failed to join chat. Please try again.');
                    navigate('/');
                    return;
                }
            }

            console.log('Current Session before check:', currentSession);
            if (!currentSession) return;

            // Fallback if backend fails to return ID (should be generated by backend)
            if (!currentSession.chatChannelId) {
                console.warn('chatChannelId missing from backend, deriving from appointmentId');
                currentSession.chatChannelId = `chat_${appointmentId}`;
            }

            const client = StreamChat.getInstance(apiKey);

            try {
                // Prevent consecutive calls or reconnecting if already connected
                if (client.userID !== currentSession.userId) {
                    if (client.userID) {
                        await client.disconnectUser();
                    }
                    await client.connectUser(
                        {
                            id: currentSession.userId,
                            name: currentSession.userId, // Ideally fetch user name
                            image: `https://getstream.io/random_png/?id=${currentSession.userId}&name=${currentSession.userId}`,
                        },
                        currentSession.chatToken
                    );
                }
            } catch (error) {
                console.error('Error connecting user:', error);
            }

            const newChannel = client.channel('messaging', currentSession.chatChannelId, {
                name: `Appointment Chat`,
            });

            await newChannel.watch();

            setChatClient(client);
            setChannel(newChannel);
            setLoading(false);
        };

        initChat();

        return () => {
            // Cleanup logic if needed. 
            // Note: Disconnecting on unmount might be aggressive if the user navigates back quickly.
            // But for now, let's keep it simple.
            if (chatClient) {
                // chatClient.disconnectUser(); 
                // Commenting out disconnect to prevent "Consecutive calls" issues on rapid remounts
                // since we check userID on mount.
            }
        };
    }, [appointmentId, sessionData, setSession, navigate]);

    if (loading) return (
        <div className="flex justify-center items-center h-screen bg-background-light">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-cta"></div>
        </div>
    );

    const { theme } = useTheme();

    const isChatExpired = sessionData?.postConsultChatExpiresAt && new Date() > new Date(sessionData.postConsultChatExpiresAt);

    return (
        <div className="h-screen flex flex-col font-body bg-background-light dark:bg-background-dark">
            <div className="bg-white dark:bg-surface shadow-sm p-4 flex justify-between items-center border-b border-gray-50 dark:border-white/5 z-10">
                <div className="flex items-center gap-3">
                    <Button variant="ghost" size="sm" onClick={() => navigate('/')} className="pl-0 text-text-secondary dark:text-text-secondary hover:text-cta hover:bg-transparent dark:hover:bg-transparent">
                        <FaArrowLeft className="mr-1" /> Back
                    </Button>
                    <h2 className="text-lg font-heading font-bold text-text-primary dark:text-text-primary">Appointment Chat</h2>
                </div>
            </div>
            <div className="flex-1 overflow-hidden" style={{ height: 'calc(100vh - 64px)' }}>
                <Chat client={chatClient} theme={`messaging ${theme}`}>
                    <Channel channel={channel}>
                        <Window>
                            <ChannelHeader />
                            <MessageList />
                            {isChatExpired ? (
                                <div className="p-4 bg-gray-100 dark:bg-gray-800 text-center text-gray-500 dark:text-gray-400 border-t border-gray-200 dark:border-gray-700">
                                    This chat session has expired. You cannot send new messages.
                                </div>
                            ) : (
                                <MessageInput focus />
                            )}
                        </Window>
                        <Thread />
                    </Channel>
                </Chat>
            </div>
        </div>
    );
};

export default ChatPage;
